name: fight-predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - _tflow_select=2.3.0=mkl
  - alabaster=0.7.12=py37_0
  - anaconda=2018.12=py37_0
  - anaconda-client=1.7.2=py37_0
  - anaconda-navigator=1.9.7=py37_0
  - anaconda-project=0.8.2=py37_0
  - appnope=0.1.0=py37_0
  - appscript=1.0.1=py37h1de35cc_1
  - asn1crypto=0.24.0=py37_0
  - astor=0.7.1=py37_0
  - astroid=2.1.0=py37_0
  - astropy=3.1=py37h1de35cc_0
  - atomicwrites=1.2.1=py37_0
  - attrs=18.2.0=py37h28b3542_0
  - babel=2.6.0=py37_0
  - backcall=0.1.0=py37_0
  - backports=1.0=py37_1
  - backports.functools_lru_cache=1.5=py_2
  - backports.os=0.1.1=py37_0
  - backports.shutil_get_terminal_size=1.0.0=py37_2
  - backports.tempfile=1.0=py_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.6.3=py37_0
  - bitarray=0.8.3=py37h1de35cc_0
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - blaze=0.11.3=py37_0
  - bleach=3.0.2=py37_0
  - blosc=1.14.4=hd9629dc_0
  - bokeh=1.0.2=py37_0
  - boto=2.49.0=py37_0
  - bottleneck=1.2.1=py37h1d22016_1
  - bzip2=1.0.6=h1de35cc_5
  - c-ares=1.15.0=h1de35cc_1
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2018.11.29=py37_0
  - cffi=1.11.5=py37h6174b99_1
  - chardet=3.0.4=py37_1
  - click=7.0=py37_0
  - cloudpickle=0.6.1=py37_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.1=py37_0
  - conda=4.7.5=py37_0
  - conda-build=3.18.5=py37_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.3.10=py37_0
  - conda-verify=3.4.2=py_0
  - contextlib2=0.5.5=py37_0
  - cryptography=2.4.2=py37ha12b0ac_0
  - curl=7.63.0=ha441bb4_1000
  - cycler=0.10.0=py37_0
  - cython=0.29.2=py37h0a44026_0
  - cytoolz=0.9.0.1=py37h1de35cc_1
  - dask=1.0.0=py37_0
  - dask-core=1.0.0=py37_0
  - datashape=0.5.4=py37_1
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py37_0
  - defusedxml=0.5.0=py37_1
  - distributed=1.25.1=py37_0
  - docutils=0.14=py37_0
  - et_xmlfile=1.0.1=py37_0
  - expat=2.2.6=h0a44026_0
  - fastcache=1.0.2=py37h1de35cc_2
  - ffmpeg=4.0=h01ea3c9_0
  - filelock=3.0.10=py37_0
  - flask=1.0.2=py37_1
  - flask-cors=3.0.7=py37_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - future=0.17.1=py37_0
  - get_terminal_size=1.0.0=h7520d66_0
  - gettext=0.19.8.1=h15daf44_3
  - gevent=1.3.7=py37h1de35cc_1
  - glib=2.56.2=hd9629dc_0
  - glob2=0.6=py37_1
  - gmp=6.1.2=hb37e062_1
  - gmpy2=2.0.8=py37h6ef4df4_2
  - graphite2=1.3.13=h2098e52_0
  - greenlet=0.4.15=py37h1de35cc_0
  - h5py=2.8.0=py37h878fce3_3
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - heapdict=1.0.0=py37_2
  - html5lib=1.0.1=py37_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py37_0
  - imageio=2.4.1=py37_0
  - imagesize=1.1.0=py37_0
  - importlib_metadata=0.6=py37_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - isort=4.3.4=py37_0
  - itsdangerous=1.1.0=py37_0
  - jasper=2.0.14=h636a363_1
  - jbig=2.1=h4d881f8_0
  - jdcal=1.4=py37_0
  - jedi=0.13.2=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - jupyterlab=0.35.3=py37_0
  - jupyterlab_server=0.2.0=py37_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - keyring=17.0.0=py37_0
  - kiwisolver=1.0.1=py37h0a44026_0
  - krb5=1.16.1=hddcf347_7
  - lazy-object-proxy=1.3.1=py37h1de35cc_2
  - libarchive=3.3.3=h786848e_5
  - libcurl=7.63.0=h051b688_1000
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - liblief=0.9.0=h2a1bed3_0
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.35=ha441bb4_0
  - libprotobuf=3.8.0=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.8.0=ha12b0ac_4
  - libtiff=4.0.9=hcb84e12_2
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.8=hab757c2_1
  - libxslt=1.1.32=hb819dd2_0
  - llvmlite=0.26.0=py37h8c7ce04_0
  - locket=0.2.0=py37_1
  - lxml=4.2.5=py37hef8c89e_0
  - lz4-c=1.8.1.2=h1de35cc_0
  - lzo=2.10=h362108e_2
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.0=py37h1de35cc_0
  - matplotlib=3.0.2=py37h54f8f79_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.1=144
  - mkl-service=1.1.2=py37hfbe908c_5
  - mkl_fft=1.0.6=py37h27c97d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - mock=3.0.5=py37_0
  - more-itertools=4.3.0=py37_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.1=h3018a27_3
  - mpmath=1.1.0=py37_0
  - msgpack-python=0.5.6=py37h04f5b5a_1
  - multipledispatch=0.6.0=py37_0
  - navigator-updater=0.2.1=py37_0
  - nbconvert=5.4.0=py37_1
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - networkx=2.2=py37_1
  - nltk=3.4=py37_1
  - nose=1.3.7=py37_2
  - notebook=5.7.4=py37_0
  - numba=0.41.0=py37h6440ff4_0
  - numexpr=2.6.8=py37h7413580_0
  - numpy=1.15.4=py37hacdab7b_0
  - numpy-base=1.15.4=py37h6575580_0
  - numpydoc=0.8.0=py37_0
  - odo=0.5.1=py37_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openpyxl=2.5.12=py37_0
  - openssl=1.1.1a=h1de35cc_0
  - packaging=18.0=py37_0
  - pandas=0.23.4=py37h6440ff4_0
  - pandoc=1.19.2.1=ha5e8f32_1
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - partd=0.3.9=py37_0
  - path.py=11.5.0=py37_0
  - pathlib2=2.3.3=py37_0
  - patsy=0.5.1=py37_0
  - pcre=8.42=h378b8a2_0
  - pep8=1.7.1=py37_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.3.0=py37hb68e598_0
  - pip=18.1=py37_0
  - pixman=0.38.0=h1de35cc_0
  - pkginfo=1.4.2=py37_1
  - pluggy=0.8.0=py37_0
  - ply=3.11=py37_0
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.7=py37_0
  - psutil=5.4.8=py37h1de35cc_0
  - ptyprocess=0.6.0=py37_0
  - py=1.7.0=py37_0
  - py-lief=0.9.0=py37hd4eaf27_0
  - py-opencv=3.4.2=py37h7c891bd_1
  - pycosat=0.6.3=py37h1de35cc_0
  - pycparser=2.19=py37_0
  - pycrypto=2.6.1=py37h1de35cc_9
  - pycurl=7.43.0.2=py37ha12b0ac_0
  - pygments=2.3.1=py37_0
  - pylint=2.2.2=py37_0
  - pyodbc=4.0.25=py37h0a44026_0
  - pyopenssl=18.0.0=py37_0
  - pyparsing=2.3.0=py37_0
  - pyqt=5.9.2=py37h655552a_2
  - pysocks=1.6.8=py37_0
  - pytables=3.4.4=py37h13cba08_0
  - pytest=4.0.2=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.5.0=py37_0
  - pytest-doctestplus=0.2.0=py37_0
  - pytest-openfiles=0.3.1=py37_0
  - pytest-remotedata=0.3.1=py37_0
  - python=3.7.1=haf84260_7
  - python-dateutil=2.7.5=py37_0
  - python-libarchive-c=2.8=py37_6
  - python.app=2=py37_9
  - pytz=2018.7=py37_0
  - pywavelets=1.0.1=py37h1d22016_0
  - pyyaml=3.13=py37h1de35cc_0
  - pyzmq=17.1.2=py37h1de35cc_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=0.5.3=py37_0
  - qtconsole=4.4.3=py37_0
  - qtpy=1.5.2=py37_0
  - readline=7.0=h1de35cc_5
  - requests=2.21.0=py37_0
  - rope=0.11.0=py37_0
  - ruamel_yaml=0.15.46=py37h1de35cc_0
  - scikit-image=0.14.1=py37h0a44026_0
  - scikit-learn=0.20.1=py37h27c97d8_0
  - scipy=1.1.0=py37h1410ff5_2
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.6.3=py37_0
  - shap=0.28.5=py37h1702cab_0
  - simplegeneric=0.8.1=py37_2
  - singledispatch=3.4.0.3=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.12.0=py37_0
  - snappy=1.1.7=he62c110_3
  - snowballstemmer=1.2.1=py37_0
  - sortedcollections=1.0.1=py37_0
  - sortedcontainers=2.1.0=py37_0
  - sphinx=1.8.2=py37_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-websupport=1.1.0=py37_1
  - spyder=3.3.2=py37_0
  - spyder-kernels=0.3.0=py37_0
  - sqlalchemy=1.2.15=py37h1de35cc_0
  - sqlite=3.26.0=ha441bb4_0
  - statsmodels=0.9.0=py37h1d22016_0
  - sympy=1.3=py37_0
  - tblib=1.3.2=py37_0
  - tensorboard=1.13.1=py37haf313ee_0
  - tensorflow=1.13.1=mkl_py37h70c3834_0
  - tensorflow-base=1.13.1=mkl_py37h66b1bf0_0
  - tensorflow-estimator=1.13.0=py_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py37_0
  - tornado=5.1.1=py37h1de35cc_0
  - tqdm=4.28.1=py37h28b3542_0
  - traitlets=4.3.2=py37_0
  - unicodecsv=0.14.1=py37_0
  - unixodbc=2.3.7=h1de35cc_0
  - urllib3=1.24.1=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.14.1=py37_0
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - wrapt=1.10.11=py37h1de35cc_2
  - wurlitzer=1.0.2=py37_0
  - xlrd=1.2.0=py37_0
  - xlsxwriter=1.1.2=py37_0
  - xlwings=0.15.1=py37_0
  - xlwt=1.3.0=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.5=h0a44026_1
  - zict=0.1.3=py37_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - absl-py==0.7.1
    - automat==0.7.0
    - constantly==15.1.0
    - cssselect==1.0.3
    - entrypoints==0.3
    - flake8==3.7.8
    - gast==0.2.2
    - google-pasta==0.1.6
    - grpcio==1.20.1
    - hyperlink==18.0.0
    - incremental==17.5.0
    - keras==2.2.4
    - parsel==1.5.1
    - protobuf==3.7.1
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.4
    - pycodestyle==2.5.0
    - pydispatcher==2.0.5
    - pyflakes==2.1.1
    - pyhamcrest==1.9.0
    - queuelib==1.5.0
    - scrapy==1.6.0
    - service-identity==18.1.0
    - sklearn==0.0
    - tb-nightly==1.14.0a20190301
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019030115
    - twisted==18.9.0
    - w3lib==1.20.0
    - zope-interface==4.6.0
prefix: /Users/charlespierse/anaconda3

